### ISSUE TITLE
Where can I find paper?

### ISSUE THREAD

**Issue by Sanster** [cvlab-stonybrook/PaperEdge#1]
Thank you for open source your research code. I find your PRESENTATION page [here](https://s2022.siggraph.org/presentation/?id=papers_839&sess=sess160) but didn't find a paper download link. Where can I find the paper? Thanks

**Comment by wkema** [comment]
You can find the paper on ACM website:
https://dl.acm.org/doi/10.1145/3528233.3530756

I have also updated the README with the links to the paper and supplementary material. Hopefully ACM won't require me to delete it lol.
