### ISSUE TITLE
Background data problem

### ISSUE THREAD

**Issue by ursaminor0401** [cvlab-stonybrook/PaperEdge#15]
I'm trying to train Tnet on my own real data and doc3d data, would you mind sharing the data in data/bgtex.txt？
I found through the path that part of the data comes from dtd, but the other part of texmix I did not find the source.

**Comment by Noah2018** [comment]
I have the same question as well，I can't find all the data mentioned in bgtex.txt, can someone pls help with this?

**Comment by wkema** [comment]
ah sry I almost forgot where I got the rest of the texture images. I believe the `texmix` is from here:
https://github.com/abin24/Textures-Dataset
hmmm it might be a little inappropriate that I did not cite this author's paper...tho the data the author collected is public.

**Comment by wkema** [comment]
a second thought: I was using the texture datasets because I was working on texture classification. So texture datasets first came into my mind when I was thinking about the bg texture. Since the application is on the real world scenario, I wonder if using ImageNet or OpenImage as bg could yield better results lol.

**Comment by Noah2018** [comment]
> ah sry I almost forgot where I got the rest of the texture images. I believe the `texmix` is from here: https://github.com/abin24/Textures-Dataset hmmm it might be a little inappropriate that I did not cite this author's paper...tho the data the author collected is public.

Thx for the info, much appreciated, I can try other blank images as bgtex as well

**Comment by renmada** [comment]
How about `dtd` data？

**Comment by wkema** [comment]
> How about `dtd` data？

DTD is here...tho I don't think these datasets are critical to reproduce the results.
https://www.robots.ox.ac.uk/~vgg/data/dtd/

**Comment by ursaminor0401** [comment]
> ah sry I almost forgot where I got the rest of the texture images. I believe the `texmix` is from here: https://github.com/abin24/Textures-Dataset hmmm it might be a little inappropriate that I did not cite this author's paper...tho the data the author collected is public.

Thanks for the information and advice, It helped me a lot!
