### ISSUE TITLE
Share image segmentation annotation tool

### ISSUE THREAD

**Issue by tinoater** [cvlab-stonybrook/PaperEdge#22]
In your paper you mention that you had a tool based on GrabCut that took about 5s per image to annotate. I'd find this tool really helpful in building my own dataset - are you able to share the tool?

**Comment by wkema** [comment]
sry I could not find my original code as I have graduated for a long time...

I think I copied a lot of code from this repo
https://github.com/chocopoule/grabcutweb

I only added some func to read and save the results from/to the lab server.

Hope this helps

**Comment by tinoater** [comment]
Thanks for the response! I'll take a look
