### ISSUE TITLE
A miss module in code

### ISSUE THREAD

**Issue by hanquansanren** [cvlab-stonybrook/PaperEdge#6]
hi ke, 
I try to train your model, but I found here the following seems amiss:
I can not found where is the module `tsdeform`
https://github.com/cvlab-stonybrook/PaperEdge/blob/8c7382634f095d5e5e95a9fbb838826ad29d4b63/networks/tps_warp.py#L182

**Comment by wkema** [comment]
oh sorry I should have deleted everything within `__name__ == '__main__'` block. I used it as an easy way for unittest, which is a bad practice. But it should not affect the training...

**Comment by hanquansanren** [comment]
OK, I see, thanks for your response
